# TCL File Generated by Component Editor 18.1
# Tue Jul 18 18:21:41 BRT 2023
# DO NOT MODIFY


# 
# InliersOutliers "InliersOutliers" v1.0
#  2023.07.18.18:21:41
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module InliersOutliers
# 
set_module_property DESCRIPTION ""
set_module_property NAME InliersOutliers
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP meus_componentes
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME InliersOutliers
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Inliers_Interface
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Inliers_Check.v VERILOG PATH Inliers_Check.v
add_fileset_file Inliers_Interface.v VERILOG PATH Inliers_Interface.v TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL Inliers_Interface
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Inliers_Check.v VERILOG PATH Inliers_Check.v
add_fileset_file Inliers_Interface.v VERILOG PATH Inliers_Interface.v


# 
# parameters
# 


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point Leitura
# 
add_interface Leitura avalon end
set_interface_property Leitura addressUnits WORDS
set_interface_property Leitura associatedClock clock
set_interface_property Leitura associatedReset reset
set_interface_property Leitura bitsPerSymbol 8
set_interface_property Leitura burstOnBurstBoundariesOnly false
set_interface_property Leitura burstcountUnits WORDS
set_interface_property Leitura explicitAddressSpan 0
set_interface_property Leitura holdTime 0
set_interface_property Leitura linewrapBursts false
set_interface_property Leitura maximumPendingReadTransactions 0
set_interface_property Leitura maximumPendingWriteTransactions 0
set_interface_property Leitura readLatency 0
set_interface_property Leitura readWaitStates 0
set_interface_property Leitura readWaitTime 0
set_interface_property Leitura setupTime 0
set_interface_property Leitura timingUnits Cycles
set_interface_property Leitura writeWaitTime 0
set_interface_property Leitura ENABLED true
set_interface_property Leitura EXPORT_OF ""
set_interface_property Leitura PORT_NAME_MAP ""
set_interface_property Leitura CMSIS_SVD_VARIABLES ""
set_interface_property Leitura SVD_ADDRESS_GROUP ""

add_interface_port Leitura read read Input 1
add_interface_port Leitura readdata readdata Output 32
set_interface_assignment Leitura embeddedsw.configuration.isFlash 0
set_interface_assignment Leitura embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment Leitura embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment Leitura embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Escrita
# 
add_interface Escrita avalon end
set_interface_property Escrita addressUnits WORDS
set_interface_property Escrita associatedClock clock
set_interface_property Escrita associatedReset reset
set_interface_property Escrita bitsPerSymbol 8
set_interface_property Escrita burstOnBurstBoundariesOnly false
set_interface_property Escrita burstcountUnits WORDS
set_interface_property Escrita explicitAddressSpan 32
set_interface_property Escrita holdTime 0
set_interface_property Escrita linewrapBursts false
set_interface_property Escrita maximumPendingReadTransactions 0
set_interface_property Escrita maximumPendingWriteTransactions 0
set_interface_property Escrita readLatency 0
set_interface_property Escrita readWaitTime 1
set_interface_property Escrita setupTime 0
set_interface_property Escrita timingUnits Cycles
set_interface_property Escrita writeWaitStates 1
set_interface_property Escrita writeWaitTime 1
set_interface_property Escrita ENABLED true
set_interface_property Escrita EXPORT_OF ""
set_interface_property Escrita PORT_NAME_MAP ""
set_interface_property Escrita CMSIS_SVD_VARIABLES ""
set_interface_property Escrita SVD_ADDRESS_GROUP ""

add_interface_port Escrita write_address address Input 4
add_interface_port Escrita write write Input 1
add_interface_port Escrita writedata writedata Input 32
set_interface_assignment Escrita embeddedsw.configuration.isFlash 0
set_interface_assignment Escrita embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment Escrita embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment Escrita embeddedsw.configuration.isPrintableDevice 0

